### ISSUE TITLE
Investigate some open (health?) datasets to use as demo/showcase

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/data#22]
It would be good to start building up a showcase of datasets using Seedcase, so we can show what it might look like for others.

Some requirements:

- It has an open license
- It complies with GDPR (could be personal data, as long as consent is given)
- It is on a platform that makes it easy to write a script to auto-download the files with the data (e.g. Zenodo, Dryad)
- Ideally health data, but those options are fewer

It can have one or more data resources. Ideally more than one resource. If we have a variety of options, we can select several and slowly convert them over into examples.

Once we have a dataset, I'll create a demo/example repo with the necessary infrastructure and files, as well as issues for the next steps.

**Comment by K-Beicher** [comment]
https://doi.org/10.5061/dryad.h70rxwdp5 xlsx

https://doi.org/10.5061/dryad.79cnp5j0r csv

https://doi.org/10.5061/dryad.05qfttf7g csv *

https://doi.org/10.5061/dryad.tmpg4f553 txt (bit of a mess)

https://doi.org/10.5061/dryad.tqjq2bvv9 csv

https://doi.org/10.5061/dryad.30bj3 tab-sv *

https://doi.org/10.5061/dryad.063h8 xlsx

https://doi.org/10.5061/dryad.60s6033 xlsx

**Comment by K-Beicher** [comment]
The Male Seed Beetle data set (https://doi.org/10.5061/dryad.30bj3) is a fairly straightforward single file dataset which would make for a nice easy upload. It contains strings, integers, and floats with 19 columns and about 2,500 rows.

The Free Living Birds data set (https://doi.org/10.5061/dryad.05qfttf7g) is again a single file data set, with 29 columns containing not only text and numbers, but also date related fields.

**Comment by K-Beicher** [comment]
We can always re-open this when we need more examples.
