### ISSUE TITLE
Write script to download a (small) dataset to use for testing

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/data#5]
Write a shell/bash script to download an open dataset from Zenodo or Dryad (maybe use a few), BUT NOT save the data into the Git version history.

We need to have a dataset or two to use for testing and development purposes. Not sure how this will fit into the development framework and environment but for now let's just simply add one. Not store the actual dataset in the repo, but make a script to download and save it in the project folder (but ignore tracking with Git).

**Comment by lwjohnst86** [comment]
@K-Beicher I've modified this issue to say we need a script to download (but not save to Git) data for testing Seedcase. It should be small though.

this is related to seedcase-project/seedcase#5

**Comment by K-Beicher** [comment]
This has been superseded by the Data repo.  Closing for that reason
